# Site settings
title: S3 2015
email: remy.leone@telecom-paristech.fr
description: S3++ Pozega 2015 (July 24th - August 4nd) - Life of a web request
baseurl: /s3_2015
twitter_username: remyleone
github_username:  sieben
